### ISSUE TITLE
External Bug Report: Dining Halls all 1 day off

### ISSUE THREAD

**Issue by adelq** [pennlabs/penn-mobile-android#185]
Not confirmed yet, but received a bug report that "the menus for all of the dining halls seem to be a day off (i.e., today shows yesterday's menu). I'm not sure if it's all the time but I've noticed it whenever I check out what's being served today".
Needs confirmation before it can be worked on but definitely should be looking out for it.

**Comment by adelq** [comment]
Confirm and can reproduce: our dining menus are 1 day behind

**Comment by yefim** [comment]
LOL

**Comment by adelq** [comment]
@awiss

**Comment by sachabest** [comment]
@adelq is this cross platform? Server side I'm assuming?

**Comment by adelq** [comment]
It's server-side, but I believe it's due daily menus not being updated in time. Since iOS uses the weekly menu, this bug only affects Android. pennlabs/penn-mobile-server#47 should fix this issue with a tiny decrease in caching performance.

**Comment by adelq** [comment]
I don't think this has shown up in production anymore.
