### ISSUE TITLE
Add Android testing

### ISSUE THREAD

**Issue by adelq** [pennlabs/penn-mobile-android#189]
https://www.bignerdranch.com/blog/triumph-android-studio-1-2-sneaks-in-full-testing-support/

**Comment by adelq** [comment]
https://google.github.io/android-testing-support-library/

**Comment by sachabest** [comment]
Dude.....see you in 10 years...#androidtesting

**Comment by scwu** [comment]
miss you guys @adelq @sachabest 

ok sorry. ill leave ya'll to it <3

**Comment by sachabest** [comment]
@scwu wahhhh come back
