### ISSUE TITLE
Implement Chrome Custom tabs

### ISSUE THREAD

**Issue by adelq** [pennlabs/penn-mobile-android#262]
Should be must faster than current WebView. Either way, optimize WebView performance, why is it so slow?

**Comment by adelq** [comment]
https://medium.com/ribot-labs/exploring-chrome-customs-tabs-on-android-ef427effe2f4

**Comment by andrewsi10** [comment]
Didn't see this issue until now, but Chrome Custom Tabs was added to the News section in v1.11.0.

https://github.com/pennlabs/penn-mobile-android/releases/tag/v1.11.0
