### ISSUE TITLE
Group all sections of a course into the course detail view

### ISSUE THREAD

**Issue by adelq** [pennlabs/penn-mobile-android#271]
Attach all lectures, seminars, labs under the detail view

**Comment by jasontsh** [comment]
Is this an API thing or should we really just do this from front end?

**Comment by jasontsh** [comment]
@eureika are we gonna do the expandable list?

**Comment by adelq** [comment]
This may just be a list adapter at the bottom of the lecture course view. I think a prereq for this would be fixing the scrolling on the course view.

**Comment by jasontsh** [comment]
Remember that we have actually set a preference for showing the recitations or not... If we automatically put the recitations below the course views, and hide them from the main page, are we still going to have the preference?

**Comment by adelq** [comment]
Yes, so you can open the recitation and see the associated lecture and other possible recitations for the same lecture
