### ISSUE TITLE
Add fragment animations and transitions

### ISSUE THREAD

**Issue by adelq** [pennlabs/penn-mobile-android#273]
https://github.com/lgvalle/Material-Animations

**Comment by jasontsh** [comment]
https://www.google.com/design/spec/animation/meaningful-transitions.html#

**Comment by adelq** [comment]
https://medium.com/@bherbst/fragment-transitions-with-shared-elements-7c7d71d31cbb#.bmt23te61

**Comment by adelq** [comment]
https://medium.com/ribot-labs/exploring-meaningful-motion-on-android-1cd95a4bc61d#.esgtqxgfe
