### ISSUE TITLE
Switch to new permissions model

### ISSUE THREAD

**Issue by adelq** [pennlabs/penn-mobile-android#281]
Currently, our location permission needs to be wrapped to adjust with SDK 23's new permissions model, otherwise it will crash on runtime. Unfortunately, we don't have a device to test it on, but we can emulate the device.

## Some resources
http://android-developers.blogspot.com/2015/08/building-better-apps-with-runtime.html
http://www.captechconsulting.com/blogs/runtime-permissions-best-practices-and-how-to-gracefully-handle-permission-removal
https://commonsware.com/blog/2015/08/17/random-musings-android-6p0-sdk.html

**Comment by adelq** [comment]
Marking as wontfix for now because we don't have any devices to test on.

**Comment by jasontsh** [comment]
We have a device to test on now, and now the map/transit doesn't work.

**Comment by jasontsh** [comment]
Resolved with branch merged.
