### ISSUE TITLE
Laundry Fragment

### ISSUE THREAD

**Issue by jasontsh** [pennlabs/penn-mobile-android#286]
@adelq, @dlakata,
Right now I'm thinking putting a list that has the building names, so like 
Hill
Harrison
Harnwell 
etc.
And I am wondering if there should be any more information to be stored on each list item.  Should we include the sum of all machine usable?  But that sounds not useful because there is no way all Harrison machines are in used.

 - [X] Add listing of college houses
 - [x] Add listing of floors with laundry within a college house
 - [x] Show indicators next to each floor within a college house for washer and dryer availability
 - [x] Ability to set notification on particular washer/dryer availability
 - [x] Ability to set notification on when a particular load is done

**Comment by adelq** [comment]
See pennlabs/penn-mobile-ios#83 for details

**Comment by jasontsh** [comment]
#297 done.
