### ISSUE TITLE
Change font weight for dining halls' hours

### ISSUE THREAD

**Issue by eureika** [pennlabs/penn-mobile-android#295]
![screenshot_2015-11-13-16-29-58](https://cloud.githubusercontent.com/assets/11711483/11260858/12aeaf5a-8e3d-11e5-8ca5-3008cb3d66da.png)

^ current

v mock up (can also be found under drive > projects > mobile app > mock ups)

![dining_halls_v01](https://cloud.githubusercontent.com/assets/11711483/11260865/29f57694-8e3d-11e5-96b4-9748a17540e9.jpg)

**Comment by adelq** [comment]
With both of these screenshots side by side, the original looks more polished and consistent in my opinion - there are too many font weights going on in the new version. Thoughts?
