### ISSUE TITLE
Campus help - add phone icon / change font color to #3F51B5

### ISSUE THREAD

**Issue by eureika** [pennlabs/penn-mobile-android#296]
![screenshot_2015-11-13-16-46-20](https://cloud.githubusercontent.com/assets/11711483/11261373/f6051696-8e41-11e5-88f9-bfe15eca8681.png)

^ current

v mockup of icon (font color change not reflected)

![campus_help](https://cloud.githubusercontent.com/assets/11711483/11261375/0145ae1c-8e42-11e5-92ae-a5a78be8542d.jpg)

**Comment by eureika** [comment]
new mock up with font color updated can be found under drive > projects > mobile app > mockups

**Comment by jasontsh** [comment]
Cross reference #291

**Comment by adelq** [comment]
I'm fine with this, but maybe instead have the call button be on the side and bigger - just an idea
