### ISSUE TITLE
Use gson to serialize/deserialize favorited instructors into JSON

### ISSUE THREAD

**Issue by adelq** [pennlabs/penn-mobile-android#305]
Use gson's toJson method to serialize/deserialize favorited instructors in the preferences to real JSON. Also would require a method to convert old format to JSON on first run to preserve old preferences.

**Comment by jasontsh** [comment]
@dlakata  we really want to use JSON instead of |#|?

**Comment by dlakata** [comment]
idk |#| has a special place in my heart

**Comment by jasontsh** [comment]
Finished in #322
