### ISSUE TITLE
Hours for non-residential dining halls

### ISSUE THREAD

**Issue by dlakata** [pennlabs/penn-mobile-android#311]
Currently, hours can only be seen for residential dining halls, and the info button is shown on the menu page. Perhaps the info button could be moved to the listing of venues so that hours for all venues can seen

**Comment by adelq** [comment]
My initial thoughts for this was residential halls have it in the action menu, and nonresidential halls have it instead of the arrow on the venues listing. Not sure how feasible this is, but I think better from a layout point of view
