### ISSUE TITLE
Text on about screen is missing

### ISSUE THREAD

**Issue by dlakata** [pennlabs/penn-mobile-android#313]
![device-2016-01-21-115423](https://cloud.githubusercontent.com/assets/3457673/12487587/ca772b6a-c035-11e5-80b3-adaccc0c3585.png)

**Comment by jasontsh** [comment]
What should it really be?

**Comment by dlakata** [comment]
the text from https://github.com/pennlabs/penn-mobile-android/blob/master/PennMobile/src/main/java/com/pennapps/labs/pennmobile/AboutFragment.java

**Comment by adelq** [comment]
Confirmed

**Comment by jasontsh** [comment]
Hint: styles.  Change all the style of the main stuff with 0dp to wrap_content.  MAKE SURE THAT THE HOME PAGE STILL WORKS
