### ISSUE TITLE
Use floating action button for map and transit

### ISSUE THREAD

**Issue by adelq** [pennlabs/penn-mobile-android#314]

**Comment by jasontsh** [comment]
@eureika @adelq what would the floating button do?  Do you think a layout similar to Google Map should be fine?

**Comment by jasontsh** [comment]
![screenshot_20160216-211642](https://cloud.githubusercontent.com/assets/9397267/13097842/c1566754-d4f2-11e5-85d6-334d6ab9cfb2.png)
![screenshot_20160216-193738](https://cloud.githubusercontent.com/assets/9397267/13097845/c38e375e-d4f2-11e5-976e-01b8279514f4.png)

**Comment by jasontsh** [comment]
These are what I have so far- please tell me the spacing, and how it should look like now that the search button is on the bottom, what should happen when the button is clicked.

**Comment by adelq** [comment]
* Search button should definitely be the bottom one, and I think following the Google Maps style with a bright search and a white/gray layers would work much better.
* Pink needs adjustment, @eureika should choose
* I think button spacing is fine
* For now, when both buttons are clicked they should do same thing as before, though we should add more transition animations so it's clear what's happening

**Comment by eureika** [comment]
![maps](https://cloud.githubusercontent.com/assets/11711483/13199044/d2f24aee-d7e7-11e5-839d-0b23984ee2ba.jpg)

- Accent/secondary color change to #E91E63 (Pink 500 on Material Design)
- Two icons should be My Location and Directions
- What is the layer?
- My Location Icon will change to blue while and only when tapped

**Comment by eureika** [comment]
@jasontsh floating buttons spacing is not accurate so don't change that yet - i'll make a new issue

**Comment by adelq** [comment]
* I like this pink, it pops out
* Layers are for selecting the 3 transit routes
The rest sounds good to me :)
