### ISSUE TITLE
Add link/support for Halal food request form

### ISSUE THREAD

**Issue by adelq** [pennlabs/penn-mobile-android#318]
Currently, the Halal food program has a request form that must be filled out an hour in advance. There should be a link to access this Google form from the app, maybe as an overflow item on the dining venues fragment.

Current Link: http://upennmsa.org/halalrsvp/

**Comment by jasontsh** [comment]
@adelq do you want this as a menu item (hidden) or ifroom or...?

**Comment by adelq** [comment]
Closing this because the RSVP form is no longer in use
