### ISSUE TITLE
Directory Design Revamp

### ISSUE THREAD

**Issue by eureika** [pennlabs/penn-mobile-android#320]
![directory](https://cloud.githubusercontent.com/assets/11711483/12698814/50098818-c775-11e5-99b8-b8479b21fdbb.jpg)

![directory_grid](https://cloud.githubusercontent.com/assets/11711483/12698813/50093052-c775-11e5-94d9-c3466c877e58.jpg)

**Comment by jasontsh** [comment]
@dlakata  could you check if the notes are going to be implemented in back end or front end?

**Comment by jasontsh** [comment]
@eureika  I can change the image of the cross, but sadly I can't change the color of them by myself.  Could you give me the crosses?  Thank you!

**Comment by dlakata** [comment]
the notes will be implemented in front end

**Comment by jasontsh** [comment]
Finished in #322
