### ISSUE TITLE
Directory Search Design Revamp

### ISSUE THREAD

**Issue by eureika** [pennlabs/penn-mobile-android#323]
![directory_search_empty](https://cloud.githubusercontent.com/assets/11711483/12869047/380c18da-cce2-11e5-9fb9-96a691c59be2.jpg)
![directory_search](https://cloud.githubusercontent.com/assets/11711483/12869045/3808e5b6-cce2-11e5-9972-b486acbd393f.jpg)
![directory_search_grid](https://cloud.githubusercontent.com/assets/11711483/12869046/380b379e-cce2-11e5-8f6f-3c82212a8fec.jpg)

**Comment by adelq** [comment]
I like this a lot, with the exception of historical searches which I think should have a different icon, a la [material design](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B6Okdz75tqQsUENaeGRvVks0Tms/patterns_search_expandable2.png)

**Comment by eureika** [comment]
Recent searches could use this icon?
![image](https://cloud.githubusercontent.com/assets/11711483/13029793/05764aee-d264-11e5-9628-d99d4bc4ecc0.png)

**Comment by adelq** [comment]
^yes, this is great

**Comment by jasontsh** [comment]
Done in #322
