### ISSUE TITLE
Dining Menu Design Revamp

### ISSUE THREAD

**Issue by eureika** [pennlabs/penn-mobile-android#326]
![dining_menu](https://cloud.githubusercontent.com/assets/11711483/12869624/24617422-ccf3-11e5-96b0-dbc4790670c8.jpg)
![dining_menu_grid](https://cloud.githubusercontent.com/assets/11711483/12869623/245f3fae-ccf3-11e5-9ae2-a00369e70ee8.jpg)

**Comment by adelq** [comment]
![i-bleed-maize-and-blue_design](https://cloud.githubusercontent.com/assets/929309/13025597/3dc8e612-d1d9-11e5-8471-88f94ebf16b3.png)

**Comment by lilyidi** [comment]
Haven't made tabs for meals yet. Waiting for @jasontsh 's new classes.
