### ISSUE TITLE
Dining Hours Design Revamp

### ISSUE THREAD

**Issue by eureika** [pennlabs/penn-mobile-android#328]
![dining_hours](https://cloud.githubusercontent.com/assets/11711483/13029774/9a0ca384-d263-11e5-9575-14ad1b410042.jpg)

**Comment by adelq** [comment]
I'm not a fan of this layout, I would prefer an info button in the toolbar and the meals as tabs. The light gray still bothers me, it's too light

**Comment by jasontsh** [comment]
Finished.
