### ISSUE TITLE
Maps (Search) Design Revamp

### ISSUE THREAD

**Issue by eureika** [pennlabs/penn-mobile-android#337]
![maps](https://cloud.githubusercontent.com/assets/11711483/13199354/1d4ede64-d7f1-11e5-9f5e-e7f1a1920d21.jpg)
![maps_search_result](https://cloud.githubusercontent.com/assets/11711483/13199353/1d4ece88-d7f1-11e5-8cb6-c6f9e01c0824.jpg)

Still thinking about search as to what kind of searches we should suggest/show.
Or we could skip that part as a whole like the app is now.

**Comment by eureika** [comment]
![maps_search](https://cloud.githubusercontent.com/assets/11711483/13199405/ca208272-d7f2-11e5-9dd8-0b5b6b26b6f3.jpg)

Search probably the line along directory's search should be fine.

**Comment by adelq** [comment]
I can dig this, not sure how feasible/creepy it is to show "Current Address:"

**Comment by eureika** [comment]
We do need a white bar at the bottom for layout reasons though.
Any suggestions?

**Comment by adelq** [comment]
Maybe whether Penn transit is currently in service?

**Comment by jasontsh** [comment]
http://developer.android.com/training/location/display-address.html
This is the current address thing, and the challenge would be implementing this on a fragment based application like Penn Mobile.

**Comment by jasontsh** [comment]
I also need the hard-coded distance between the two floating buttons and the divider to the boarders

**Comment by jasontsh** [comment]
After setting the circles, they are no longer "clickable".  Do you want anything to happen when they are clicked?  The current marker would be clickable and show a picture.

**Comment by eureika** [comment]
I'll get you the distance sometimes this week.
So with the circles, if you tap on them, the location icon should pop up from that location instead and the previous one turn to red... is that hard?

**Comment by jasontsh** [comment]
I'll try my best.  It is going to be very very hard to implement the current location- what is your plan for displaying things there?
