### ISSUE TITLE
Maps (Directions) Design Revamp

### ISSUE THREAD

**Issue by eureika** [pennlabs/penn-mobile-android#338]
![maps_directions](https://cloud.githubusercontent.com/assets/11711483/13199640/ead6e7da-d7f8-11e5-8bf1-b924e7f5caf8.jpg)

Little too complicated to show in design, but you should be able to combine maps + transit with the three designs.

**Comment by adelq** [comment]
This is fantastic, now comes time to implement it though :) @jasontsh

**Comment by jasontsh** [comment]
Do you want me to override the enter key to something more like a search or something?  :+1: I'm doing relatively well regarding the layout, will work on the api calls

**Comment by adelq** [comment]
http://stackoverflow.com/a/3205405

**Comment by jasontsh** [comment]
The circles on the line is a little bit too hard to implement... is there any color of solid lines @eureika prefers?

**Comment by eureika** [comment]
It's a screenshot from Google Maps so you can ignore that. Anything most convenient for you is fine. If you want to specify, the default blue listed under My Location should suffice.

**Comment by jasontsh** [comment]
@eureika do you want the colors to be different on the route: the part where the user takes the transit is in a different color than the start/end walking routes' colors?

**Comment by jasontsh** [comment]
Also need to know what happens after the bus button is clicked.

**Comment by eureika** [comment]
All good?
Yeah I think bus can be pink or primary blue and walk can be current color.
@adelq ?

**Comment by adelq** [comment]
I really love all these changes, waiting to get them in the app

**Comment by jasontsh** [comment]
The transit api is down again, so we'll wait a while :p

**Comment by jasontsh** [comment]
I can't get the time for the route if the transit api is down :p Also, the support for adding the time marker is not great at the moment.

**Comment by adelq** [comment]
Working on transit API right now

**Comment by adelq** [comment]
I just created a pull request to fix the bug over at pennlabs/penn-mobile-server#71
