### ISSUE TITLE
Courses Design Revamp

### ISSUE THREAD

**Issue by eureika** [pennlabs/penn-mobile-android#339]
![courses](https://cloud.githubusercontent.com/assets/11711483/13239190/5f6d373a-d9a6-11e5-9395-d647b005900e.jpg)

Search should also be similar to directory.

**Comment by adelq** [comment]
:+1:

**Comment by jasontsh** [comment]
I thought the bar underneath the all should be yellow... like the accent color.

**Comment by adelq** [comment]
UMich is out, pink is in

**Comment by lilyidi** [comment]
@eureika 
![screenshot_2016-03-21-21-06-36](https://cloud.githubusercontent.com/assets/9397415/13939214/6d5f06b6-efa9-11e5-93f2-2608ab728d75.png)

**Comment by eureika** [comment]
Changes to make:
- Background to FAFAFA
- Course title font size little too big? Hard to tell.
