### ISSUE TITLE
Courses Info Design Revamp

### ISSUE THREAD

**Issue by eureika** [pennlabs/penn-mobile-android#340]
![courses_details](https://cloud.githubusercontent.com/assets/11711483/13240956/e65ecd4a-d9b4-11e5-94bf-a9b047778491.jpg)

Not much change from current, but sizes of boxes are more uniform now as well as color.

**Comment by adelq** [comment]
The interaction patterns definitely have to change so that the scrolling goes over the map, but implementation is difficult. Maybe @jasontsh can take another shot at it?

**Comment by eureika** [comment]
I meant that map will just stay where it is -- everything else goes under the map

**Comment by adelq** [comment]
Yes, exactly

**Comment by jasontsh** [comment]
The question here is should the view pager be visible...  Like the switch on top from all to favorites.

**Comment by adelq** [comment]
Just though of something, FAB for favoriting a course from within the course info page

**Comment by jasontsh** [comment]
Done.
