### ISSUE TITLE
Campus Help summaries

### ISSUE THREAD

**Issue by dlakata** [pennlabs/penn-mobile-android#349]
**HELP line**
24-hour-a-day phone number for members of the Penn community who are seeking time sensitive help in navigating Penn’s resources for health and wellness.
**Police emergency MERT**
Call for all criminal or medical emergencies.
**Penn Police General**
Call for all non-emergencies
**Penn Walk**
Call this number to have a Public safety officer walk you home between 30th to 43rd Streets and Market Street to Baltimore Avenue .
**Penn Ride**
Call for Penn Ride services
**CAPS**
CAPS main number. Call anytime to reach CAPS

**Comment by adelq** [comment]
Some of these sound super redundant, especially the last two. Suggestions:
**Penn Ride**
On-Call shuttle service to or from off-campus locations.
**CAPS**
Counseling and Psychological Services main number, available any time and for Emergencies

**Comment by jasontsh** [comment]
I am not completely sure how it should look like.

**Comment by eureika** [comment]
Is this for android penn mobile?

**Comment by jasontsh** [comment]
For both (I believe), but this issue is for android.  @adelq I'll need to go back to them to check the suggested summaries.
