### ISSUE TITLE
Dining/Directory/Courses standardize cards and font

### ISSUE THREAD

**Issue by eureika** [pennlabs/penn-mobile-android#355]
![issue01](https://cloud.githubusercontent.com/assets/11711483/14268580/8bb73438-faaa-11e5-8642-a53660eea665.jpg)

Really like how the dining page is looking so far.
- For all activities, there are three lines, and all lines should have same font sizes and weight/style(medium or regular) unless mentioned
- Work with me if sizes don't match

**Comment by lilyidi** [comment]
@eureika 
So should the font sizes, weights/styles be more like how Dining is now?

**Comment by eureika** [comment]
@lilyidi yes that'd be great!
