### ISSUE TITLE
Dining arrow loading + change color

### ISSUE THREAD

**Issue by eureika** [pennlabs/penn-mobile-android#356]
![issue02](https://cloud.githubusercontent.com/assets/11711483/14268675/c75cb5de-faab-11e5-8ff1-c74538dce856.jpg)

- Arrow/next button looks like this when you scroll down and scroll back up and loads the icon a while later
- Change icon color to #737373
- Open icon should be same width as Closed

**Comment by lilyidi** [comment]
- The loading icon is there when info about the dining hall is being retrieved through the API and then changes to the arrow when all the info has been loaded.

**Comment by adelq** [comment]
@lilyidi I think what Reika is referring to is that scrolling down then up on the dining page momentarily reverts back to a loading indicator, when it has already fetched the data.

**Comment by lilyidi** [comment]
@adelq Oh, I see. I'm not sure how I can change that though because it calls the API every time it sees that a list item is residential?

**Comment by jasontsh** [comment]
Fixed by #373 and #368
