### ISSUE TITLE
Directory/Courses alignment/search/back button

### ISSUE THREAD

**Issue by eureika** [pennlabs/penn-mobile-android#357]
![issue03](https://cloud.githubusercontent.com/assets/11711483/14268723/43364e0e-faac-11e5-8700-c1c1dc531bfe.jpg)

- Directory back button doesn't work aka why is it there if we don't have it in courses
- D... shows up next to search and that shouldn't be happening
- If text in search bar, X sign should be white
- Align the add contacts with the star icon, and standardize icon size with other icons/star
- Change icon color to #737373

**Comment by eureika** [comment]
![issue04](https://cloud.githubusercontent.com/assets/11711483/14268824/12ead7be-faad-11e5-8266-816b85bd98be.jpg)

**Comment by jasontsh** [comment]
@adelq We have looked into the problem of D... before, but it was futile.  Lemme try again this time

**Comment by jasontsh** [comment]
@adelq @dlakata The fact that now we have search suggestions and stuff actually make it easier for me to hide and set the titles

**Comment by jasontsh** [comment]
@eureika the cross has the same color as the hint, as default.  Do you really want to change it?

**Comment by adelq** [comment]
I also think the add to contacts icon is way too large relative to the rest of the app, should be probably half the size

**Comment by eureika** [comment]
@jasontsh can we at least make the icon itself white, and not the search? if not i'll give up.
@adelq yeah mentioned it in the issue

**Comment by jasontsh** [comment]
![screenshot_20160411-211629](https://cloud.githubusercontent.com/assets/9397267/14447121/cd35435c-002a-11e6-8853-bfa70f1e59cd.png)
![screenshot_20160411-211636](https://cloud.githubusercontent.com/assets/9397267/14447122/ce9064ca-002a-11e6-9b90-29786edc4812.png)

Closing as fixed.
