### ISSUE TITLE
Course info change formatting and color

### ISSUE THREAD

**Issue by eureika** [pennlabs/penn-mobile-android#358]
![issue05](https://cloud.githubusercontent.com/assets/11711483/14268865/5ddaf36c-faad-11e5-8370-0f00282cab90.jpg)

- Change blue background behind course title to #3F51B5 
- Description shouldn't be bold but probably medium. Correct me if I'm wrong
- Not enough padding on top and needs little more (refer to dining/directory) on the left

**Comment by lilyidi** [comment]
@eureika How's this?
![screenshot_2016-04-09-15-08-28 1](https://cloud.githubusercontent.com/assets/9397415/14405818/1722b6f6-fe65-11e5-8032-16e05661218b.png)

**Comment by adelq** [comment]
I don't think the map should be that large, it takes up a lot of space from the description etc and isn't very useful besides for the first time, and is especially annoying while the scrolling behavior isn't fixed
