### ISSUE TITLE
Use Bottom Sheets for Course View

### ISSUE THREAD

**Issue by adelq** [pennlabs/penn-mobile-android#382]
Bottom sheets are now in Android Support Library 23.2
http://www.materialdoc.com/bottom-sheets/

**Comment by jasontsh** [comment]
@tifchang do you know what we could do with this?

**Comment by tifchang** [comment]
will take a look

**Comment by adelq** [comment]
This is from the original design concept by Reika, just check out how Google Maps works. Essentially, the main content frame should scroll over the map at the top.
