### ISSUE TITLE
Dining listview loading icon reflow

### ISSUE THREAD

**Issue by adelq** [pennlabs/penn-mobile-android#385]
In the dining listview, scrolling up and down results in weirdness with reflowing and re-rendering the loading icons.

Steps to replicate:
1. Open dining
2. Scroll up and down
3. Observe as list items reflow every single time and rerender the loading indicator

**Comment by jasontsh** [comment]
#373 has already fixed it...

**Comment by jasontsh** [comment]
Sorry, but this IS fixed by #373
