### ISSUE TITLE
Back button does not work in transit

### ISSUE THREAD

**Issue by adelq** [pennlabs/penn-mobile-android#387]
Steps to replicate:
1. Go to transit
2. Search for destination (ex: parc)
3. Press on-screen back
4. No change...

**Comment by adelq** [comment]
Back button is broken in a lot of places actually, Map is also affected and I've gotten stuck in a weird back state several times now

**Comment by jasontsh** [comment]
We are supposed to push the new pull request of a newly made map page.  Could you please look at it?

**Comment by jasontsh** [comment]
Fixed by having a new version of map and removing transit. #361.
