### ISSUE TITLE
Swiping left on NSO items does not do anything

### ISSUE THREAD

**Issue by adelq** [pennlabs/penn-mobile-android#396]

**Comment by jasontsh** [comment]
We will work on NSO next year, probably a revamp of everything.

**Comment by adelq** [comment]
Then leave the issue open so that it's marked as a known issue, alternative is to rip out NSO now.

**Comment by jasontsh** [comment]
We rip out NSO...

**Comment by adelq** [comment]
It's still in the codebase though, NsoFragment.java still has these bugs
