### ISSUE TITLE
Unable to trigger "open in new tab" for News

### ISSUE THREAD

**Issue by adelq** [pennlabs/penn-mobile-android#398]

**Comment by andrewsi10** [comment]
Open new tab should trigger for DP and 34th Street, although they open the wrong website. It doesn't trigger for UTB. I'm currently working on a fix for this bug.

**Comment by adelq** [comment]
Good call, I was only testing UTB, that's exactly the correct. Feel free to
mark this as a duplicate and close it. Thanks!

**Comment by adelq** [comment]
Duplicate of #389
