### ISSUE TITLE
Difficult to trigger "add to contacts" swipe in directory (tab swipe + favorites swipe conflict)

### ISSUE THREAD

**Issue by adelq** [pennlabs/penn-mobile-android#399]

**Comment by jasontsh** [comment]
We can figure something out for next year.  This year's NSO was to get things done asap.

**Comment by jasontsh** [comment]
How do you want to do this for registrar?

**Comment by adelq** [comment]
What do you mean? This bug is for directory

**Comment by jasontsh** [comment]
Well regardless, do you think it's better to not hide the button underneath? or what do you think should we do it.  The design is such that if you really select a tile swiping left you'll get to the hidden button.

**Comment by adelq** [comment]
The point is that if you swipe left, you will swipe into favorites, not to uncover the hidden button, so it's nearly impossible to actually access. It did not used to have tabs, so swiping worked fine.

**Comment by jasontsh** [comment]
@tifchang thinks that it's a good feature for the hidden drawer, but we can make it more obvious:
https://github.com/daimajia/AndroidSwipeLayout/blob/master/library/src/main/java/com/daimajia/swipe/SwipeLayout.java
We can make the first tile to open and close at the beginning of onResume.  @andrewsi10 will work on this later.
