### ISSUE TITLE
Going back to News tab does not work properly

### ISSUE THREAD

**Issue by andrewsi10** [pennlabs/penn-mobile-android#410]
Steps to reproduce from the master branch:

1. Open News tab (image 1)
2. Open some other tab from the side menu (e.g. Courses)
3. Press back button to return to News tab; a section of the top bar disappears (image 2)

Expected: the top bar should not disappear
Bug: top bar disappears after about half a second

![image 1](https://cloud.githubusercontent.com/assets/12239257/20231523/829cf426-a830-11e6-9b1c-6944382e85b6.png)
![image 2](https://cloud.githubusercontent.com/assets/12239257/20231532/96c52ba8-a830-11e6-9dc0-04c36b9b5917.png)

**Comment by jasontsh** [comment]
Won't fix

**Comment by adelq** [comment]
Why not?
