### ISSUE TITLE
Gray bar at bottom of maps view

### ISSUE THREAD

**Issue by adelq** [pennlabs/penn-mobile-android#434]
Not sure what this is for, seems like a bug since it is blank

**Comment by ZhouMichael** [comment]
I think it's supposed to display the nearest building / address

**Comment by adelq** [comment]
Oh, then it probably only displays a gray bar since I'm currently very far
away. Bar shouldn't be shown if no results found.

**Comment by andrewsi10** [comment]
The gray bar has been removed. However, we've also disabled access to the maps section until the API is fixed (the current API returns DuBois College House when you search up Harrison), which will take a month or two.
