### ISSUE TITLE
Use adaptive icons

### ISSUE THREAD

**Issue by adelq** [pennlabs/penn-mobile-android#437]
Just use navy background, remove white. Icon needs redesign in any case

https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html

**Comment by andrewsi10** [comment]
I'll talk to our designer about this.

**Comment by andrewsi10** [comment]
Because of more urgent items on the roadmap and the new app icon that was introduced in spring 2018, this was not implemented until PR https://github.com/pennlabs/penn-mobile-android/pull/483.
