### ISSUE TITLE
News Back Button

### ISSUE THREAD

**Issue by adamdom** [pennlabs/penn-mobile-android#445]
Just playing around with the new edition (looks awesome btw) and when you enter a news vendor then go back (either with the X or with the back button) the menu icon that is usually in the top left, is now a back arrow that does not work. I am able to hit the physical back button on my phone and go back so its obviously not critical, but just something to note :)

**Comment by andrewsi10** [comment]
Yup I noticed the same issue last night; however I've been having trouble reproducing the bug.

**Comment by andrewsi10** [comment]
Managed to reproduce the bug. Steps:

1. Open dining and open a dining hall
2. Press back twice to return to home screen
3. Open news and select a publication
4. Press back to return to news. There will be a back button that does not work.

**Comment by andrewsi10** [comment]
Fixed by #491.
