### ISSUE TITLE
Add laundry reminder gone in Laundry redesign

### ISSUE THREAD

**Issue by adelq** [pennlabs/penn-mobile-android#453]
You know how hard it is to create a `BroadcastReceiver`? @jasontsh knows

**Comment by andrewsi10** [comment]
When we originally released the update, the new laundry API lacked support for tracking individual laundry machine statuses, so it wasn't possible to add reminders for laundry. Since then, the new API has added this feature, so we will be setting up laundry reminders next semester.

**Comment by andrewsi10** [comment]
Latest app update has laundry reminders!
