### ISSUE TITLE
Hacktober x Labs: Remove redundant OS checks

### ISSUE THREAD

**Issue by rchhaya** [pennlabs/penn-mobile-android#549]
It's time to bump up our minimum supported Android version to version 26 (O) from 18 (JELLY_BEAN_MR2). This is great because we can drop a bunch of version checks.

In Android, if we want to use a cool feature that exists in a later android version, say version 30, we have to check whether the phone's android OS is actually on version 30 or later. Here's an example: `if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1) { ... }` on line 240 of `HomeAdapter.kt`
 
Given our previous minimum was 18, we have a lot of OS checks that check whether the OS is 19,20,21,22,23,24,25 or 26, all of which are now redundant (since a minimum of 26 guarantees all devices have OS version >= 26). Let's remove them from all the source code!

PS: The version code mapping between symbol and number are found here: https://apilevels.com/

**Comment by rohanmalik0** [comment]
Hello Please assign this task to me. I can do it for you

**Comment by rchhaya** [comment]
Sure! Assigned. Also please remove the `@Requires(API)` annotation for the levels below or equal to 26

**Comment by rohanmalik0** [comment]
Thanks for Assigning me this project. I will do it by time.

**Comment by rchhaya** [comment]
Hi, checking in about this issue

**Comment by rchhaya** [comment]
Hi, since Hacktoberfest has ended, I'm removing you from issue and solving it internally. Thanks for your interest.
